from migration_project.routers import (
    boscosend_configs,
    cft_tcp,
    exceptions,
    flow_actions,
    flows,
    generation_jobs,
    mapping_rules,
    moncft_configs,
    partners,
    pipeline,
    scripts,
    servers,
    stats,
    stg_cft_tcp,
    transfers,
    ssh_pull,
)

__all__ = [
    "boscosend_configs",
    "cft_tcp",
    "exceptions",
    "flow_actions",
    "flows",
    "generation_jobs",
    "mapping_rules",
    "moncft_configs",
    "partners",
    "pipeline",
    "scripts",
    "servers",
    "stats",
    "stg_cft_tcp",
    "transfers",
    "ssh_pull",
]
